messages:
  outgoing_queue: fp_to_idb
  incoming_queue: idb_to_fp

:aws:
  :s3_mode: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:s3_mode] %>
  :access_key_id: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:access_key_id] %>
  :secret_access_key: <%= Rails.application.credentials[Rails.env.to_sym][:aws][:secret_access_key] %>
  :region: us-east-2
